# Machine Learning

In [33]:
from sklearn.model_selection import train_test_split # Dividir os dados entre treino e teste
from sklearn.metrics import accuracy_score, confusion_matrix # Avaliação do modelo com precisão e matriz de confusão
from sklearn.neighbors import KNeighborsClassifier # Algoritmo de KNN - Classificação por vizinhos (aproximação)
import pandas as pd
from scipy import stats

In [34]:
dataset = pd.read_csv('iris.csv', sep=',')

In [35]:
dataset.head()

   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [36]:
dataset.shape

(150, 5)

In [37]:
dados = pd.DataFrame(dataset) # Transformar dados em dataframe

In [38]:
dados.describe() # Analise e estatisticas dos dados

       sepal length  sepal width  petal length  petal width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [39]:
dados['class'].value_counts() # Ver quantos registros tem de cada planta, para saber se o treinamento faz sentido

# Precisa ter uma quantidade equalizada de dados

class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

## Separação dos dados

In [40]:
previsores = dados.iloc[:,0:4].values # Seleciona todas os valores, das colunas de 0 até 4 (todas as colunas, exceto a classe)
classe = dados.iloc[:,4].values # Seleciona todos os valores da coluna 4 (classe)

### Separação 70/30

In [41]:
X_treinamento, X_teste, Y_treinamento, Y_teste = train_test_split(previsores, classe, test_size=0.3, random_state=0)

# Separação dos dados de 70% para treinamento, e 30% para testes

In [42]:
len(X_treinamento) # Validar se a separacao esta correta (tem que retornar 105)

105

## Treinar o algoritmo

In [43]:
knn = KNeighborsClassifier(n_neighbors=3) # Escolhe o algoritmo KNN e quantidade de vizinhos (3)

In [44]:
knn.fit(X_treinamento, Y_treinamento) # Função para treinar o modelo com dados

KNeighborsClassifier(n_neighbors=3)

In [45]:
prova = knn.predict(X_teste) # Função para prever/testar o modelo

In [46]:
prova # Respostas

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

## Calcular quantidade de acertos

In [47]:
acertos = accuracy_score(Y_teste, prova)
acertos

0.9777777777777777

### Matriz de confusão

In [48]:
confusao = confusion_matrix(Y_teste, prova)
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])